<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Effortless.Cli.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Plossum.CommandLine.Core" Version="0.3.0.14" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Effortless.Cli.Tests" />
    <InternalsVisibleTo Include="Effortless.Cli.E2E" />
  </ItemGroup>

</Project>
