using System.Diagnostics;
using System.Reflection;
using System.Text.Json;
using Xunit;

namespace Effortless.Cli.Tests;

public sealed class DevopsGenerationTests
{
    [Fact(DisplayName = "devops-generation-drift: generated files match the rulebook")]
    public async Task GeneratedFilesMatchTheRulebook()
    {
        var result = await RunNode("scripts/generate-from-rulebook.mjs", "--check");

        Assert.True(
            result.ExitCode == 0,
            $"Generator drift detected.{Environment.NewLine}{result.StandardOutput}{result.StandardError}");
    }

    [Fact(DisplayName = "devops-coverage-gate: every retained option has a test")]
    public void EveryRetainedOptionHasATest()
    {
        using var rulebook = LoadRulebook();
        var root = rulebook.RootElement;
        var retainedDispositions = root.GetProperty("Dispositions")
            .GetProperty("data")
            .EnumerateArray()
            .Where(row => row.GetProperty("IsRetained").GetBoolean())
            .Select(row => row.GetProperty("DispositionId").GetString()!)
            .ToHashSet(StringComparer.Ordinal);
        var testCounts = root.GetProperty("TestCases")
            .GetProperty("data")
            .EnumerateArray()
            .GroupBy(row => row.GetProperty("PrimaryOption").GetString()!)
            .ToDictionary(group => group.Key, group => group.Count(), StringComparer.Ordinal);
        var untested = root.GetProperty("CliOptions")
            .GetProperty("data")
            .EnumerateArray()
            .Where(row =>
                retainedDispositions.Contains(
                    row.GetProperty("Disposition").GetString()!))
            .Select(row => row.GetProperty("CliOptionId").GetString()!)
            .Where(option => !testCounts.TryGetValue(option, out var count) || count == 0)
            .Order(StringComparer.Ordinal)
            .ToArray();

        Assert.True(
            untested.Length == 0,
            $"Retained options without test cases:{Environment.NewLine}{string.Join(Environment.NewLine, untested)}");
    }

    // HelpCommand renders "  {Flag,-26} {HelpSummary}", so a summary must fit
    // 80 - 2 - 26 - 1 columns for -help to stay inside an 80-column terminal
    // (meta-help-width). Enforced here so an over-long summary fails at
    // authoring time rather than only in the E2E golden.
    private const int MaxHelpSummaryLength = 51;

    [Fact(DisplayName = "help-summary-width: every HelpSummary fits the -help column budget")]
    public void EveryRetainedOptionHasAHelpSummaryUnder72Columns()
    {
        using var rulebook = JsonDocument.Parse(
            File.ReadAllText(
                Path.Combine(
                    RepositoryRoot,
                    "effortless-rulebook",
                    "effortless-rulebook.json")));
        var root = rulebook.RootElement;
        var retained = root.GetProperty("Dispositions").GetProperty("data")
            .EnumerateArray()
            .ToDictionary(
                row => row.GetProperty("DispositionId").GetString()!,
                row => row.GetProperty("IsRetained").GetBoolean(),
                StringComparer.Ordinal);

        var problems = new List<string>();
        foreach (var option in root.GetProperty("CliOptions").GetProperty("data")
                     .EnumerateArray()
                     .Where(row =>
                         retained[row.GetProperty("Disposition").GetString()!]))
        {
            var id = option.GetProperty("CliOptionId").GetString()!;
            var summary =
                option.TryGetProperty("HelpSummary", out var value)
                && value.ValueKind == JsonValueKind.String
                    ? value.GetString()!
                    : string.Empty;
            if (string.IsNullOrWhiteSpace(summary))
            {
                problems.Add($"{id}: HelpSummary is empty");
            }
            else if (summary.Length > MaxHelpSummaryLength)
            {
                problems.Add(
                    $"{id}: HelpSummary is {summary.Length} chars (max {MaxHelpSummaryLength})");
            }
        }

        Assert.True(
            problems.Count == 0,
            string.Join(Environment.NewLine, problems));
    }

    [Fact(DisplayName = "readme-commands-block-matches-rulebook: README block is generated")]
    public async Task ReadmeCommandBlockMatchesTheRulebook()
    {
        var readme = await File.ReadAllTextAsync(
            Path.Combine(RepositoryRoot, "README.md"));
        Assert.Contains(
            "<!-- cli-commands:start -->",
            readme,
            StringComparison.Ordinal);
        Assert.Contains(
            "<!-- cli-commands:end -->",
            readme,
            StringComparison.Ordinal);

        // The block is regenerated by the same script that emits CliOptions.g.cs,
        // so --check reporting no drift is what proves it matches the rulebook.
        var result = await RunNode(
            "scripts/generate-from-rulebook.mjs",
            "--check");

        Assert.True(
            result.ExitCode == 0,
            result.StandardOutput + result.StandardError);
    }

    [Fact(DisplayName = "devops-test-manifest: every required manifest case exists in code")]
    public void EveryRequiredManifestCaseExistsInCode()
    {
        var required = LoadManifest(
                "tests/Effortless.Cli.E2E/TestManifest.g.json")
            .Concat(
                LoadManifest(
                    "tests/Effortless.Cli.Tests/TestManifest.g.json"))
            .Where(entry => entry.Priority is "P0" or "P1")
            .Select(entry => entry.Id)
            .ToHashSet(StringComparer.Ordinal);
        var assemblies = new[]
        {
            Assembly.GetExecutingAssembly(),
            typeof(Effortless.Cli.E2E.Suites.ManifestCoverageTests).Assembly,
        };
        var implemented = assemblies
            .SelectMany(assembly => assembly.GetTypes())
            .SelectMany(type => type.GetMethods())
            .SelectMany(method =>
                method.GetCustomAttributes<FactAttribute>()
                    .Select(attribute => attribute.DisplayName))
            .Where(displayName => !string.IsNullOrWhiteSpace(displayName))
            .Select(displayName => displayName!.Split(':', 2)[0])
            .ToHashSet(StringComparer.Ordinal);
        var missing = required
            .Except(implemented)
            .Order(StringComparer.Ordinal)
            .ToArray();

        Assert.True(
            missing.Length == 0,
            $"Missing P0/P1 manifest tests:{Environment.NewLine}{string.Join(Environment.NewLine, missing)}");
    }

    [Fact(DisplayName = "devops-release-dry-run: release guards and dry run are safe")]
    public async Task ReleaseGuardsAndDryRunAreSafe()
    {
        using var directory = new TestDirectory();
        Directory.CreateDirectory(directory.File("scripts"));
        File.Copy(
            Path.Combine(RepositoryRoot, "scripts", "release.sh"),
            directory.File("scripts/release.sh"));
        File.WriteAllText(
            directory.File("package.json"),
            """{"name":"@effortlessapi/cli","version":"2026.901.1200"}""");

        Assert.Equal(
            0,
            (await RunProcess("git", directory.Path, "init", "-b", "main")).ExitCode);
        Assert.Equal(
            0,
            (await RunProcess("git", directory.Path, "add", ".")).ExitCode);
        Assert.Equal(
            0,
            (await RunProcess(
                "git",
                directory.Path,
                "-c",
                "user.name=Effortless Tests",
                "-c",
                "user.email=tests@example.invalid",
                "commit",
                "-m",
                "fixture")).ExitCode);

        var dryRun = await RunProcess(
            "bash",
            directory.Path,
            "scripts/release.sh",
            "--dry-run");

        Assert.Equal(0, dryRun.ExitCode);
        Assert.Contains("Dry run:", dryRun.StandardOutput, StringComparison.Ordinal);
        Assert.Contains("Would publish", dryRun.StandardOutput, StringComparison.Ordinal);
        Assert.Equal(
            "2026.901.1200",
            JsonDocument.Parse(
                    File.ReadAllText(directory.File("package.json")))
                .RootElement
                .GetProperty("version")
                .GetString());

        Assert.Equal(
            0,
            (await RunProcess(
                "git",
                directory.Path,
                "switch",
                "-c",
                "feature")).ExitCode);
        var wrongBranch = await RunProcess(
            "bash",
            directory.Path,
            "scripts/release.sh",
            "--dry-run");
        Assert.NotEqual(0, wrongBranch.ExitCode);
        Assert.Contains(
            "release must run from main",
            wrongBranch.StandardError,
            StringComparison.Ordinal);

        Assert.Equal(
            0,
            (await RunProcess("git", directory.Path, "switch", "main")).ExitCode);
        File.AppendAllText(directory.File("package.json"), Environment.NewLine);
        var dirtyTree = await RunProcess(
            "bash",
            directory.Path,
            "scripts/release.sh",
            "--dry-run");
        Assert.NotEqual(0, dirtyTree.ExitCode);
        Assert.Contains(
            "clean working tree",
            dirtyTree.StandardError,
            StringComparison.Ordinal);
    }

    [Fact(DisplayName = "devops-ci-matrix: CI builds and tests all supported operating systems")]
    public void CiBuildsAndTestsAllSupportedOperatingSystems()
    {
        var workflow = File.ReadAllText(
            Path.Combine(RepositoryRoot, ".github", "workflows", "ci.yml"));

        Assert.Contains("ubuntu-latest", workflow, StringComparison.Ordinal);
        Assert.Contains("macos-latest", workflow, StringComparison.Ordinal);
        Assert.Contains("windows-latest", workflow, StringComparison.Ordinal);
        Assert.Contains("dotnet build Effortless.Cli.sln", workflow, StringComparison.Ordinal);
        Assert.Contains("dotnet test Effortless.Cli.sln", workflow, StringComparison.Ordinal);
        Assert.Contains("node scripts/generate-from-rulebook.mjs --check", workflow, StringComparison.Ordinal);
        Assert.Contains("node scripts/validate-rulebook.mjs", workflow, StringComparison.Ordinal);
        Assert.Contains("npm run test:package", workflow, StringComparison.Ordinal);
    }

    private static JsonDocument LoadRulebook()
    {
        return JsonDocument.Parse(
            File.ReadAllText(
                Path.Combine(
                    RepositoryRoot,
                    "effortless-rulebook",
                    "effortless-rulebook.json")));
    }

    private static IReadOnlyList<ManifestEntry> LoadManifest(string relativePath)
    {
        return JsonSerializer.Deserialize<List<ManifestEntry>>(
                   File.ReadAllText(Path.Combine(RepositoryRoot, relativePath)),
                   new JsonSerializerOptions
                   {
                       PropertyNameCaseInsensitive = true,
                   })
               ?? throw new InvalidOperationException(
                   $"Could not parse generated manifest '{relativePath}'.");
    }

    private static async Task<ProcessResult> RunNode(
        string script,
        params string[] arguments)
    {
        return await RunProcess(
            "node",
            RepositoryRoot,
            [script, .. arguments]);
    }

    private static async Task<ProcessResult> RunProcess(
        string executable,
        string workingDirectory,
        params string[] arguments)
    {
        using var process = new Process
        {
            StartInfo = new ProcessStartInfo(executable)
            {
                WorkingDirectory = workingDirectory,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
            },
        };
        foreach (var argument in arguments)
        {
            process.StartInfo.ArgumentList.Add(argument);
        }

        if (!process.Start())
        {
            throw new InvalidOperationException(
                $"Could not start '{executable}'.");
        }

        var standardOutput = process.StandardOutput.ReadToEndAsync();
        var standardError = process.StandardError.ReadToEndAsync();
        await process.WaitForExitAsync();

        return new ProcessResult(
            process.ExitCode,
            await standardOutput,
            await standardError);
    }

    private static string RepositoryRoot
    {
        get
        {
            var directory = new DirectoryInfo(AppContext.BaseDirectory);
            while (directory is not null)
            {
                if (File.Exists(
                        Path.Combine(
                            directory.FullName,
                            "effortless-rulebook",
                            "effortless-rulebook.json")))
                {
                    return directory.FullName;
                }

                directory = directory.Parent;
            }

            throw new DirectoryNotFoundException(
                "Could not locate the effortless-cli repository root.");
        }
    }

    private sealed record ManifestEntry(
        string Id,
        string Suite,
        string Priority,
        string Status,
        bool Slow,
        bool Interactive);

    private sealed record ProcessResult(
        int ExitCode,
        string StandardOutput,
        string StandardError);
}
