/*******************************************
 Initially Generated by SSoT.me - codee42 & odxml42
 Created By: EJ Alexandra - 2017
             An Abstract Level, llc
 License:    Mozilla Public License 2.0
 *******************************************/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using SassyMQ.SSOTME.Lib.RMQActors;
using System.IO;
using System.Diagnostics;
using SSoTme.OST.Lib.CLIOptions;
using SSoTme.OST.Lib.Extensions;
using SassyMQ.Lib.RabbitMQ;
using System.Text.RegularExpressions;
using System.Linq;
using Newtonsoft.Json;

namespace SSoTme.OST.Lib.DataClasses
{
    public partial class ProjectTranspiler
    {
        [JsonIgnore]
        public Transpiler MatchedTranspiler { get; set; }

        [JsonIgnore]
        public SSoTmeCLIHandler CLIHandler { get; private set; }

        public ProjectTranspiler()
        {
            this.InitPoco();
        }

        // Helper method to check if a command line represents a remote URL transpiler
        private static bool IsRemoteUrlCommandLine(string commandLine)
        {
            if (string.IsNullOrEmpty(commandLine)) return false;

            var trimmedCmd = commandLine.Trim();

            // Check if command starts with http:// or https://
            if (trimmedCmd.StartsWith("http://", StringComparison.OrdinalIgnoreCase) ||
                trimmedCmd.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            // Check if command contains -g flag followed by a URL
            if (trimmedCmd.Contains("-g "))
            {
                var parts = trimmedCmd.Split(' ');
                var gIndex = Array.IndexOf(parts, "-g");
                if (gIndex >= 0 && gIndex + 1 < parts.Length)
                {
                    var nextPart = parts[gIndex + 1];
                    return nextPart.StartsWith("http://", StringComparison.OrdinalIgnoreCase) ||
                           nextPart.StartsWith("https://", StringComparison.OrdinalIgnoreCase);
                }
            }

            return false;
        }

        public bool IsSSoTTranspiler { get; set; }

        public override string ToString()
        {
            var outputFileName = String.Empty;
            if (!ReferenceEquals(this.CLIHandler, null) && !ReferenceEquals(this.CLIHandler.OutputFileSet, null))
            {
                var outputFileSet = this.CLIHandler.OutputFileSet;
                if (!ReferenceEquals(outputFileSet, null) && System.Linq.Enumerable.Any(outputFileSet.FileSetFiles))
                {
                    outputFileName = String.Format(" ({0})", System.Linq.Enumerable.First(outputFileSet.FileSetFiles).RelativePath);
                }
            }
            var files = String.Format("{0}{1}", this.RelativePath, outputFileName).PadRight(40);
            return String.Format("{0} :: {1}", files, this.CommandLine);
        }

        public ProjectTranspiler(string relativePath, SSOTMEPayload result, string pinnedVersion = null)
        : this()
        {
            bool localCommand = (ReferenceEquals(result, null));
            this.Name = localCommand ? "LocalCommand" : result.Transpiler.Name;
            this.PinnedVersion = pinnedVersion;

            this.RelativePath = relativePath.SafeToString().Replace("\\", "/");
            var lowerCLI = Environment.CommandLine.ToLower().Replace("\\", "/");
            var cmd0 = Environment.CommandLine;
            if (lowerCLI.Contains("/ssotme.exe")) cmd0 = cmd0.Substring(lowerCLI.IndexOf("/ssotme.exe") + "/ssotme.exe".Length);
            else if (lowerCLI.Contains("/effortless.exe")) cmd0 = cmd0.Substring(lowerCLI.IndexOf("/effortless.exe") + "/effortless.exe".Length);
            else if (lowerCLI.Contains("/aicapture.exe")) cmd0 = cmd0.Substring(lowerCLI.IndexOf("/aicapture.exe") + "/aicapture.exe".Length);
            else if (lowerCLI.Contains("/aic.exe")) cmd0 = cmd0.Substring(lowerCLI.IndexOf("/aic.exe") + "/aic.exe".Length);
            else if (lowerCLI.Contains("/ssotme.ost.cli.dll")) cmd0 = cmd0.Substring(lowerCLI.IndexOf("/ssotme.ost.cli.dll") + "/ssotme.ost.cli.dll".Length);
            else if (lowerCLI.Contains("/aicapture.ost.cli.dll")) cmd0 = cmd0.Substring(lowerCLI.IndexOf("/aicapture.ost.cli.dll") + "/aicapture.ost.cli.dll".Length);            
            else if (lowerCLI.Contains("/ssotme")) cmd0 = cmd0.Substring(lowerCLI.IndexOf("/ssotme") + "/ssotme".Length);
            else if (lowerCLI.Contains("/aicapture")) cmd0 = cmd0.Substring(lowerCLI.IndexOf("/aicapture") + "/aicapture".Length);
            else if (lowerCLI.Contains("/effortless")) cmd0 = cmd0.Substring(lowerCLI.IndexOf("/aicapture") + "/aicapture".Length);
            else if (lowerCLI.Contains("/aic")) cmd0 = cmd0.Substring(lowerCLI.IndexOf("/aic") + "/aic".Length);

            // some common errors - on install we should remove all these prefixes from the CommandLine in the json
            cmd0 = cmd0.Trim(" '\"".ToCharArray());
            if (cmd0.StartsWith("/ssotme ")) {
                cmd0 = cmd0.Substring("/ssotme ".Length);
            }
            if (cmd0.StartsWith("/aic ")) {
                cmd0 = cmd0.Substring("/aic ".Length);
            }
            if (cmd0.StartsWith("/aicapture ")) {
                cmd0 = cmd0.Substring("/aicapture ".Length);
            }
            if (cmd0.StartsWith("/effortless ")) {
                cmd0 = cmd0.Substring("/effortless ".Length);
            }
            if (cmd0.StartsWith("install ")) {
                cmd0 = cmd0.Substring("install ".Length);
            }
            if (cmd0.StartsWith("-install ")) {
                cmd0 = cmd0.Substring("-install ".Length);
            }
            if (cmd0.StartsWith("ssotme ")) {
                cmd0 = cmd0.Substring("ssotme ".Length);
            }
            if (cmd0.StartsWith("aic ")) {
                cmd0 = cmd0.Substring("aic ".Length);
            }
            if (cmd0.StartsWith("aicapture ")) {
                cmd0 = cmd0.Substring("aicapture ".Length);
            }
            if (cmd0.StartsWith("effortless ")) {
                cmd0 = cmd0.Substring("effortless ".Length);
            }
            if (cmd0.StartsWith("effortless.exe ")) {
                cmd0 = cmd0.Substring("effortless.exe ".Length);
            }
            cmd0 = cmd0.Trim(" '\"".ToCharArray());
            Console.WriteLine($"COMMAND LINE: {cmd0}");
            this.CommandLine = cmd0;
            this.MatchedTranspiler = localCommand ? default(Transpiler) : result.Transpiler;
        }

        /// <summary>
        /// If the CommandLine contains an embedded version (e.g. "author/package/tool/v2025.12.25.1915")
        /// that doesn't match PinnedVersion, update the CommandLine to match.
        /// Returns true if the CommandLine was modified.
        /// </summary>
        internal bool SyncCommandLineVersion()
        {
            if (String.IsNullOrEmpty(this.PinnedVersion) || String.IsNullOrEmpty(this.CommandLine)) return false;
            var parts = this.CommandLine.Split(' ');
            var toolPart = parts[0];
            var segments = toolPart.Split('/');
            if (segments.Length < 2) return false;
            var lastSegment = segments[segments.Length - 1];
            if (!lastSegment.StartsWith("v", StringComparison.OrdinalIgnoreCase) || lastSegment.Length < 2 || !Char.IsDigit(lastSegment[1])) return false;
            if (String.Equals(lastSegment, this.PinnedVersion, StringComparison.OrdinalIgnoreCase)) return false;
            segments[segments.Length - 1] = this.PinnedVersion;
            parts[0] = String.Join("/", segments);
            this.CommandLine = String.Join(" ", parts);
            return true;
        }

        internal void Rebuild(SSoTmeProject project, bool debugOption, bool ignoreErrors = false)
        {
            // Build command line with debug flag if needed, but don't mutate this.CommandLine
            var commandLineToRun = this.CommandLine;
            if (debugOption)
            {
                commandLineToRun += " -debug";
            }

            Console.WriteLine("\n\n **** " + this.RelativePath + ": " + this.Name + " ****");
            Console.WriteLine("CommandLine:> effortless {0}", commandLineToRun);
            var transpileRootDI = new DirectoryInfo(Path.Combine(project.RootPath, $"{this.RelativePath}".Trim("\\/".ToCharArray())));
            if (!transpileRootDI.Exists) transpileRootDI.Create();

            // Store original directory to restore later
            var originalDirectory = Environment.CurrentDirectory;
            try
            {
                Environment.CurrentDirectory = transpileRootDI.FullName;

                // Create handler and set the project BEFORE parsing
                // This ensures ImportFile() uses the correct project root
                var cliHandler = new SSoTmeCLIHandler();
                cliHandler.AICaptureProject = project;
                cliHandler.commandLine = commandLineToRun;  // Use the modified command line, not this.CommandLine
                cliHandler.ParseCommand();
                cliHandler.ignoreErrors = ignoreErrors;
                if (!String.IsNullOrEmpty(cliHandler.ResolvedVersionLabel))
                {
                    Console.ForegroundColor = ConsoleColor.Blue;
                    Console.WriteLine($"cli:> {cliHandler.ResolvedVersionLabel}");
                    if (cliHandler.debug && !String.IsNullOrEmpty(cliHandler.ResolvedVersionUrl)) {
                        Console.WriteLine($"POST {cliHandler.ResolvedVersionUrl}");
                    }
                    Console.ResetColor();
                }

                var cliResult = cliHandler.TranspileProject(this, isBuildOperation: true);
                if (cliResult != 0)
                {
                    if (cliHandler.ignoreErrors)
                    {
                        Console.WriteLine($"WARNING: Transpiler '{this.Name}' failed but -ignoreErrors is set — continuing build.");
                    }
                    else
                    {
                        var errorMsg = cliHandler.result?.Exception?.Message ?? "unknown error";
                        throw new Exception($"Transpiler '{this.Name}' failed: {errorMsg}");
                    }
                }
            }
            finally
            {
                Environment.CurrentDirectory = originalDirectory;
            }
        }

        internal void Clean(SSoTmeProject project, bool preserveZFS, bool debug = false)
        {
            if (debug) {
                Console.WriteLine("CLEANING: " + this.RelativePath + ": " + this.Name);
            }
            //Console.WriteLine("CommandLine:> ssotme {0}", this.CommandLine);
            var di = new DirectoryInfo(Path.Combine(project.RootPath, this.RelativePath.Trim("\\/".ToCharArray())));
            if (!di.Exists) di.Create();
            Environment.CurrentDirectory = di.FullName;
            var zfsDI = project.GetZFSDI(this.RelativePath);

            // Derive transpiler name for ZFS file lookup.
            // Priority: LastUrl (saved from last successful run) > CommandLine URL > Name
            string transpilerName = null;

            // Best: use LastUrl — this is the actual URL that was used to create the ZFS file
            if (!String.IsNullOrEmpty(this.LastUrl))
            {
                transpilerName = this.LastUrl.SanitizeUrlForFilename();
                if (debug) Console.WriteLine($"DEBUG: Using LastUrl for ZFS lookup: {this.LastUrl} -> {transpilerName}");
            }

            // Fallback: extract URL from CommandLine for remote transpilers
            if (String.IsNullOrEmpty(transpilerName) && IsRemoteUrlCommandLine(this.CommandLine))
            {
                var trimmedCmd = this.CommandLine.Trim();
                string targetUrl = null;

                if (trimmedCmd.StartsWith("http://", StringComparison.OrdinalIgnoreCase) ||
                    trimmedCmd.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
                {
                    var parts = trimmedCmd.Split(' ');
                    targetUrl = parts[0];
                }
                else if (trimmedCmd.Contains("-g "))
                {
                    var parts = this.CommandLine.Split(' ');
                    var gIndex = Array.IndexOf(parts, "-g");
                    if (gIndex >= 0 && gIndex + 1 < parts.Length)
                    {
                        targetUrl = parts[gIndex + 1];
                    }
                }

                if (!string.IsNullOrEmpty(targetUrl))
                {
                    transpilerName = targetUrl.SanitizeUrlForFilename();
                }
            }

            // Final fallback: derive from tool name
            if (String.IsNullOrEmpty(transpilerName))
            {
                transpilerName = SSoTmeProject.LowerHyphenName(this.Name);
            }

            String zsfFileName = String.Format("{0}/{1}.zfs", zfsDI.FullName, transpilerName);
            var zfsFI = new FileInfo(zsfFileName);

            // If the expected .zfs file doesn't exist, fall back to the single .zfs file
            // in this transpiler's ZFS directory (handles version changes, name mismatches).
            if (!zfsFI.Exists && zfsDI.Exists)
            {
                var zfsFiles = zfsDI.GetFiles("*.zfs");
                if (zfsFiles.Length == 1)
                {
                    zfsFI = zfsFiles[0];
                    if (debug) Console.WriteLine($"DEBUG: Expected ZFS '{zsfFileName}' not found, using '{zfsFI.FullName}'");
                }
                else if (zfsFiles.Length > 1 && debug)
                {
                    Console.WriteLine($"DEBUG: Expected ZFS '{zsfFileName}' not found, and {zfsFiles.Length} .zfs files exist — cannot determine which to clean");
                }
            }

            if (zfsFI.Exists)
            {
                var zippedFileSet = File.ReadAllBytes(zfsFI.FullName);
                if (debug) Console.WriteLine($"DEBUG: Read {zippedFileSet.Length} bytes from {zfsFI.FullName}, calling CleanZippedFileSet()");
                zippedFileSet.CleanZippedFileSet(debug);
                if (debug) Console.WriteLine($"DEBUG: CleanZippedFileSet() completed");
                if (!preserveZFS)
                {
                    File.Delete(zfsFI.FullName);
                }
            }

            // Also remove debug XML file if it exists
            String xmlFileName = String.Format("{0}/{1}.xml", zfsDI.FullName, transpilerName);
            var xmlFI = new FileInfo(xmlFileName);
            if (xmlFI.Exists)
            {
                if (debug) Console.WriteLine($"DEBUG: Removing debug XML file: {xmlFI.FullName}");
                xmlFI.Delete();
            }
        }

        public void Describe(SSoTmeProject project)
        { 
            Console.WriteLine("\n-----------------------------------");
            Console.WriteLine("---- {0}{1}", this.Name, this.IsDisabled ? "    **** DISABLED ****" : "");
            Console.WriteLine("---- .{0}/", $"{this.RelativePath}".Replace("\\", "/"));
            Console.WriteLine("-----------------------------------");
            Console.WriteLine("\nCommand Line:> effortless {0}\n", this.CommandLine);
        }

        public bool IsAtPath(string relativePath, bool exactMatch = false)
        {
            // Normalize paths - trim leading/trailing slashes and convert to lowercase
            relativePath = relativePath.Replace("\\", "/").Trim('/').ToLower();
            var transpilerPath = this.RelativePath
                                   .SafeToString()
                                   .Replace("\\", "/")
                                   .Trim('/')
                                   .ToLower();

            // If checking from project root
            if (string.IsNullOrEmpty(relativePath))
            {
                // For exact match, only match transpilers at root (empty path)
                if (exactMatch) return string.IsNullOrEmpty(transpilerPath);
                // For non-exact match, all transpilers match
                return true;
            }

            // If transpiler is at root but we're in a subdirectory, no match
            if (string.IsNullOrEmpty(transpilerPath)) return false;

            // For exact match, only check equality
            if (exactMatch) return transpilerPath == relativePath;

            // For non-exact match, check if transpiler path starts with or equals the relative path
            return transpilerPath.StartsWith(relativePath) || transpilerPath == relativePath;
        }

        public void LoadInputAndOuputFiles(SSoTmeProject project, bool includeContents)
        {

            var cliHandler = SSoTmeCLIHandler.CreateHandler(this.CommandLine);
            if (!includeContents)
            {
                foreach (var fsf in cliHandler.FileSet.FileSetFiles)
                {
                    fsf.ClearContents();
                }
                cliHandler.inputFileSetXml = String.Empty;
                cliHandler.AICaptureProject = null;
            }

            // Derive transpiler name from command line (not from saved JSON)
            string transpilerName = SSoTmeProject.LowerHyphenName(this.Name);
            if (IsRemoteUrlCommandLine(this.CommandLine))
            {
                // Extract URL from command line - handle both "-g URL" and direct "URL" syntax
                var trimmedCmd = this.CommandLine.Trim();
                string targetUrl = null;

                if (trimmedCmd.StartsWith("http://", StringComparison.OrdinalIgnoreCase) ||
                    trimmedCmd.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
                {
                    // Direct URL syntax: extract URL as first word
                    var parts = trimmedCmd.Split(' ');
                    targetUrl = parts[0];
                }
                else if (trimmedCmd.Contains("-g "))
                {
                    // "-g URL" syntax: extract URL after -g flag
                    var parts = this.CommandLine.Split(' ');
                    var gIndex = Array.IndexOf(parts, "-g");
                    if (gIndex >= 0 && gIndex + 1 < parts.Length)
                    {
                        targetUrl = parts[gIndex + 1];
                    }
                }

                if (!string.IsNullOrEmpty(targetUrl))
                {
                    transpilerName = targetUrl.SanitizeUrlForFilename();
                }
            }

            cliHandler.AICaptureProject = project;
            cliHandler.LoadOutputFiles(transpilerName, this.GetProjectRelativePath(project), includeContents);
            cliHandler.AICaptureProject = null;

            this.CLIHandler = cliHandler;
        }

        public String GetProjectRelativePath(SSoTmeProject project)
        {
            var fullPath = Path.Combine(project.RootPath, this.RelativePath.Trim("\\/".ToCharArray()));
            return fullPath.Substring(project.RootPath.Length).Replace("\\", "/");
        }
    }
}