name: Release
on:
  push:
    branches: [ "main" ]

jobs:

  # Upload the package files from ./release/* to the GitHub Release
  release:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Fetch Package Version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=v$VERSION" >> $GITHUB_OUTPUT
          git fetch --tags
          if git tag -l | grep -q "^v$VERSION$"; then
            echo "Tag v$VERSION already exists, skipping release"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            git tag "v$VERSION"
            git push origin "v$VERSION"
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
          
      # Create initial pre-release
      - name: Create Pre-Release
        if: steps.version.outputs.skip == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.version.outputs.version }} \
            --title "Release ${{ steps.version.outputs.version }}" \
            --notes "Automated release from ${{ github.ref_name }} branch" \
            --target ${{ github.sha }} \
            --prerelease

      # Upload installers as release assets
      - name: Upload Installers to Release
        if: steps.version.outputs.skip == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.version.outputs.version }} ./release/*
        
      # Convert pre-release to latest release
      - name: Mark as Latest Release
        if: steps.version.outputs.skip == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release edit ${{ steps.version.outputs.version }} --prerelease=false --latest
