name: Python Installer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analysis:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.13 ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Code Analysis
        run: |
          pip install flake8
          flake8 . --ignore E501,F541,W293 

  build:

    permissions:
      checks: write
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7.16, 3.8.18, 3.9.22, 3.10.17, 3.11.12, 3.12.10, 3.13.3 ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r installer/requirements.txt

      - name: Run Setup
        run: |
          cd installer
          pip install .
